# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts --no-audit --production

# Copy source
COPY . .

# Use a non-root user for security (optional)
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

# Expose STDIO usage (no HTTP port)
# Define default command
CMD ["node", "src/index.js"]
